fix compile issue when using older compiler ("error C2548" on VS 2017) caused by default argument followed by parameter pack in function declaration.
replace the default arguments with function overloads that call the original function with default parameters